### ISSUE TITLE
No such module 'AppTrackingTransparency' Error

### ISSUE THREAD

**Issue by hsangtini** [vegidio-flutter/appodeal#1]
iOS error on xcode 11

No such module 'AppTrackingTransparency' Error

`SwiftAppodealFlutterPlugin.swift:1:8: error: no such module 'AppTrackingTransparency'
    import AppTrackingTransparency
`

**Comment by vegidio** [comment]
This is expected.

I created this plugin with intention to support the new tracking permission that will come in 2 weeks for iOS 14, so you need to have Xcode 12 installed to compile your project for iOS, otherwise you will get the error above. But don't worry: you need Xcode 12 to compile the project, but the code will be compatible devices using older versions of iOS.

I suggest to download Xcode 12 beta for now. The final version should be released in a couple of weeks.

**Comment by hsangtini** [comment]
Thank you very much.

I am in need of distributing the first version of the app to the appstore so I can't wait for xcode 12 release. So I forked and made a little tweak to be able to run on xcode 11.

Does that have any effect on you?

`You can't submit an app to App Store with beta software, you have to wait GM release.`

**Comment by vegidio** [comment]
No effect on me. If you managed to make it work with your tweak then great :) - I'm glad that you found a solution meanwhile.

Hopefully Xcode 12 will be released soon and we won't have this headache anymore.

**Comment by hsangtini** [comment]
I tweaked it worked by disable FAN and requestIOSTrackingAuthorization.
Your plugin is working great. Thank you! If someone want to using xcode 11, try my forked.

**Comment by vegidio** [comment]
Xcode 12 GM Seed has been released today and now we can submit apps to the App Store, so I'm closing this ticket now :)
