### ISSUE TITLE
Location Permission is being requested from the sdk explicitly

### ISSUE THREAD

**Issue by savajosa** [vegidio-flutter/appodeal#28]
After uploading app bundle in Google Play Console, it got rejected stating that I am requesting location and permissions cannot be requested for app targeted for children. Checking the app bundle explorer revealed that it is requesting, android.permission.ACCESS_COARSE_LOCATION,  android.permission.ACCESS_FINE_LOCATION, But in my app, I am not requesting such permissions. I understand that the Appodeal request such permissions for targeted ADS. But I set the consent to false in the code and did not request for location permissions, yet the play console detected that such permission are being requested
![Capture](https://user-images.githubusercontent.com/72483312/115401061-9993c080-a207-11eb-88ba-1b58c367372f.PNG)

**Comment by vegidio** [comment]
Hi,

The method `disableAndroidLocationPermissionCheck()` only stops the Appodeal plugin from checking if the app has the proper location permission, but it doesn't remove the permission itself. I understand that this doesn't look very clear in the documentation so I will try to update the docs in the next release to make it more clear.

In order to remove the location permission you should follow the official instructions from Appodeal website. Their tech support sent an e-mail to all users around 1 month ago with some information how to do that. I will attached here for you to see:

<img width="594" alt="Screenshot 2021-04-20 at 15 19 44" src="https://user-images.githubusercontent.com/934172/115404796-f2565f80-a1ed-11eb-91a2-a86da08646df.png">
