### ISSUE TITLE
Having issues building for iOS after updating FirebaseAnalytics to the latest version

### ISSUE THREAD

**Issue by Tedsterh** [vegidio-flutter/appodeal#30]
<img width="941" alt="Screenshot 2021-05-27 at 13 03 33" src="https://user-images.githubusercontent.com/56851744/119839478-19decd00-befc-11eb-8f3e-ee793da210c0.png">

**Comment by Wolfaks** [comment]
I have the same problem ... How to solve?

**Comment by vegidio** [comment]
Sorry for the late response, but this problem happens when the version of **Google Mobile Ads SDK** in your app and the version used by this Appodeal plugin don't match.

Unfortunately this is due to a limitation on how Cocoapods handle multiple versions of the same library. My only suggestion is to try to use the same version of Google Mobile Ads SDK that is used by this plugin.
